spring:
  profiles:
    active: ${LOGGING_MODE:dev}
  jackson:
    serialization:
      INDENT_OUTPUT: true

client:
  default-uri: ${HIS_BASE_URL:https://localhost/oru}
  user:
    name: ${HIS_USER:test}
    password: ${HIS_PASSWORD:test}

redcap:
  base:
    url: ${REDCAP_BASE_URL:https://redcap.localhost/api/}
  project:
    token: ${REDCAP_TOKEN:token}
    report:
      instruments: ${REDCAP_REPORT_INSTRUMENTS:informe_dinclusi_al_programa,informe_de_tancament_de_programa}
      names: ${REDCAP_REPORT_NAMES:Informe inclusion PREHAB,Informe fin PREHAB}
    format: ${REDCAP_FORMAT:json}
    type:  ${REDCAP_TYPE:flat}
    xml:
      format:  ${REDCAP_XML_FORMAT:xml}
      type:  ${REDCAP_XML_TYPE:eav}
  listener:
    timer:  ${REDCAP_LISTENER:60000}
    
fhir:
  base:
    url: ${FHIR_BASE_URL:http://localhost:8080/hapi-fhir/baseDstu3}

