spring:
  profiles:
    active: ${LOGGING_MODE:dev}
  jackson:
    serialization:
      INDENT_OUTPUT: true

his:
  default-uri: ${HIS_BASE_URL:https://localhost/oru}
  user:
    name: ${HIS_USER:test}
    password: ${HIS_PASSWORD:test}
  doctor:
    id: test

redcap:
  base:
    url: ${REDCAP_BASE_URL:https://redcap.localhost/api/}
  project:
    token: ${REDCAP_TOKEN:token}
    report:
      instruments: ${REDCAP_REPORT_INSTRUMENTS:informe_dinclusi_al_programa,informe_de_tancament_de_programa}
      names: ${REDCAP_REPORT_NAMES:Informe inclusion PREHAB,Informe fin PREHAB}
    format: ${REDCAP_FORMAT:json}
    type:  ${REDCAP_TYPE:flat}
    xml:
      format:  ${REDCAP_XML_FORMAT:xml}
      type:  ${REDCAP_XML_TYPE:eav}
  listener:
    timer:  ${REDCAP_LISTENER:60000}
  language: ${REDCAP_LANGUAGE:EN}

# 769681006 - First patient encounter
# 275647001 - Discharged from follow-up
fhir:
  base:
    url: ${FHIR_BASE_URL:http://localhost:8080/hapi-fhir-jpaserver/fhir/}
  encounter:
    codes: ${FHIR_ENCOUNTER_CODES:769681006,275647001}
    displays: ${FHIR_ENCOUNTER_DISPLAYS:First patient encounter,Discharged from follow-up}
  document:
    codes: ${FHIR_DOCUMENT_CODES:47039-3,28655-9}
    displays: ${FHIR_DOCUMENT_DISPLAYS:Hospital Admission history and physical note,Discharge Summary from Responsible Clinician}

